# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jasonzhou/Desktop/STUDY/RayTracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jasonzhou/Desktop/STUDY/RayTracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jasonzhou/Desktop/STUDY/RayTracer/CMakeFiles /Users/jasonzhou/Desktop/STUDY/RayTracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jasonzhou/Desktop/STUDY/RayTracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WalnutApp_exec

# Build rule for target.
WalnutApp_exec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WalnutApp_exec
.PHONY : WalnutApp_exec

# fast build rule for target.
WalnutApp_exec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/build
.PHONY : WalnutApp_exec/fast

Walnut/Walnut/src/Walnut/Application.o: Walnut/Walnut/src/Walnut/Application.cpp.o
.PHONY : Walnut/Walnut/src/Walnut/Application.o

# target to build an object file
Walnut/Walnut/src/Walnut/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Application.cpp.o
.PHONY : Walnut/Walnut/src/Walnut/Application.cpp.o

Walnut/Walnut/src/Walnut/Application.i: Walnut/Walnut/src/Walnut/Application.cpp.i
.PHONY : Walnut/Walnut/src/Walnut/Application.i

# target to preprocess a source file
Walnut/Walnut/src/Walnut/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Application.cpp.i
.PHONY : Walnut/Walnut/src/Walnut/Application.cpp.i

Walnut/Walnut/src/Walnut/Application.s: Walnut/Walnut/src/Walnut/Application.cpp.s
.PHONY : Walnut/Walnut/src/Walnut/Application.s

# target to generate assembly for a file
Walnut/Walnut/src/Walnut/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Application.cpp.s
.PHONY : Walnut/Walnut/src/Walnut/Application.cpp.s

Walnut/Walnut/src/Walnut/Image.o: Walnut/Walnut/src/Walnut/Image.cpp.o
.PHONY : Walnut/Walnut/src/Walnut/Image.o

# target to build an object file
Walnut/Walnut/src/Walnut/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Image.cpp.o
.PHONY : Walnut/Walnut/src/Walnut/Image.cpp.o

Walnut/Walnut/src/Walnut/Image.i: Walnut/Walnut/src/Walnut/Image.cpp.i
.PHONY : Walnut/Walnut/src/Walnut/Image.i

# target to preprocess a source file
Walnut/Walnut/src/Walnut/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Image.cpp.i
.PHONY : Walnut/Walnut/src/Walnut/Image.cpp.i

Walnut/Walnut/src/Walnut/Image.s: Walnut/Walnut/src/Walnut/Image.cpp.s
.PHONY : Walnut/Walnut/src/Walnut/Image.s

# target to generate assembly for a file
Walnut/Walnut/src/Walnut/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Image.cpp.s
.PHONY : Walnut/Walnut/src/Walnut/Image.cpp.s

Walnut/Walnut/src/Walnut/Random.o: Walnut/Walnut/src/Walnut/Random.cpp.o
.PHONY : Walnut/Walnut/src/Walnut/Random.o

# target to build an object file
Walnut/Walnut/src/Walnut/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Random.cpp.o
.PHONY : Walnut/Walnut/src/Walnut/Random.cpp.o

Walnut/Walnut/src/Walnut/Random.i: Walnut/Walnut/src/Walnut/Random.cpp.i
.PHONY : Walnut/Walnut/src/Walnut/Random.i

# target to preprocess a source file
Walnut/Walnut/src/Walnut/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Random.cpp.i
.PHONY : Walnut/Walnut/src/Walnut/Random.cpp.i

Walnut/Walnut/src/Walnut/Random.s: Walnut/Walnut/src/Walnut/Random.cpp.s
.PHONY : Walnut/Walnut/src/Walnut/Random.s

# target to generate assembly for a file
Walnut/Walnut/src/Walnut/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/Walnut/src/Walnut/Random.cpp.s
.PHONY : Walnut/Walnut/src/Walnut/Random.cpp.s

Walnut/vendor/imgui/backends/imgui_impl_glfw.o: Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_glfw.o

# target to build an object file
Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.o

Walnut/vendor/imgui/backends/imgui_impl_glfw.i: Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.i

Walnut/vendor/imgui/backends/imgui_impl_glfw.s: Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_glfw.cpp.s

Walnut/vendor/imgui/backends/imgui_impl_vulkan.o: Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_vulkan.o

# target to build an object file
Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.o
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.o

Walnut/vendor/imgui/backends/imgui_impl_vulkan.i: Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_vulkan.i

# target to preprocess a source file
Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.i
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.i

Walnut/vendor/imgui/backends/imgui_impl_vulkan.s: Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.s
.PHONY : Walnut/vendor/imgui/backends/imgui_impl_vulkan.cpp.s

Walnut/vendor/imgui/imgui.o: Walnut/vendor/imgui/imgui.cpp.o
.PHONY : Walnut/vendor/imgui/imgui.o

# target to build an object file
Walnut/vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui.cpp.o
.PHONY : Walnut/vendor/imgui/imgui.cpp.o

Walnut/vendor/imgui/imgui.i: Walnut/vendor/imgui/imgui.cpp.i
.PHONY : Walnut/vendor/imgui/imgui.i

# target to preprocess a source file
Walnut/vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui.cpp.i
.PHONY : Walnut/vendor/imgui/imgui.cpp.i

Walnut/vendor/imgui/imgui.s: Walnut/vendor/imgui/imgui.cpp.s
.PHONY : Walnut/vendor/imgui/imgui.s

# target to generate assembly for a file
Walnut/vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui.cpp.s
.PHONY : Walnut/vendor/imgui/imgui.cpp.s

Walnut/vendor/imgui/imgui_demo.o: Walnut/vendor/imgui/imgui_demo.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_demo.o

# target to build an object file
Walnut/vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_demo.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_demo.cpp.o

Walnut/vendor/imgui/imgui_demo.i: Walnut/vendor/imgui/imgui_demo.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_demo.i

# target to preprocess a source file
Walnut/vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_demo.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_demo.cpp.i

Walnut/vendor/imgui/imgui_demo.s: Walnut/vendor/imgui/imgui_demo.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_demo.s

# target to generate assembly for a file
Walnut/vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_demo.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_demo.cpp.s

Walnut/vendor/imgui/imgui_draw.o: Walnut/vendor/imgui/imgui_draw.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_draw.o

# target to build an object file
Walnut/vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_draw.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_draw.cpp.o

Walnut/vendor/imgui/imgui_draw.i: Walnut/vendor/imgui/imgui_draw.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_draw.i

# target to preprocess a source file
Walnut/vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_draw.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_draw.cpp.i

Walnut/vendor/imgui/imgui_draw.s: Walnut/vendor/imgui/imgui_draw.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_draw.s

# target to generate assembly for a file
Walnut/vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_draw.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_draw.cpp.s

Walnut/vendor/imgui/imgui_tables.o: Walnut/vendor/imgui/imgui_tables.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_tables.o

# target to build an object file
Walnut/vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_tables.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_tables.cpp.o

Walnut/vendor/imgui/imgui_tables.i: Walnut/vendor/imgui/imgui_tables.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_tables.i

# target to preprocess a source file
Walnut/vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_tables.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_tables.cpp.i

Walnut/vendor/imgui/imgui_tables.s: Walnut/vendor/imgui/imgui_tables.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_tables.s

# target to generate assembly for a file
Walnut/vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_tables.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_tables.cpp.s

Walnut/vendor/imgui/imgui_widgets.o: Walnut/vendor/imgui/imgui_widgets.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_widgets.o

# target to build an object file
Walnut/vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_widgets.cpp.o
.PHONY : Walnut/vendor/imgui/imgui_widgets.cpp.o

Walnut/vendor/imgui/imgui_widgets.i: Walnut/vendor/imgui/imgui_widgets.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_widgets.i

# target to preprocess a source file
Walnut/vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_widgets.cpp.i
.PHONY : Walnut/vendor/imgui/imgui_widgets.cpp.i

Walnut/vendor/imgui/imgui_widgets.s: Walnut/vendor/imgui/imgui_widgets.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
Walnut/vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/Walnut/vendor/imgui/imgui_widgets.cpp.s
.PHONY : Walnut/vendor/imgui/imgui_widgets.cpp.s

WalnutApp/src/WalnutApp.o: WalnutApp/src/WalnutApp.cpp.o
.PHONY : WalnutApp/src/WalnutApp.o

# target to build an object file
WalnutApp/src/WalnutApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/WalnutApp/src/WalnutApp.cpp.o
.PHONY : WalnutApp/src/WalnutApp.cpp.o

WalnutApp/src/WalnutApp.i: WalnutApp/src/WalnutApp.cpp.i
.PHONY : WalnutApp/src/WalnutApp.i

# target to preprocess a source file
WalnutApp/src/WalnutApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/WalnutApp/src/WalnutApp.cpp.i
.PHONY : WalnutApp/src/WalnutApp.cpp.i

WalnutApp/src/WalnutApp.s: WalnutApp/src/WalnutApp.cpp.s
.PHONY : WalnutApp/src/WalnutApp.s

# target to generate assembly for a file
WalnutApp/src/WalnutApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WalnutApp_exec.dir/build.make CMakeFiles/WalnutApp_exec.dir/WalnutApp/src/WalnutApp.cpp.s
.PHONY : WalnutApp/src/WalnutApp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WalnutApp_exec"
	@echo "... Walnut/Walnut/src/Walnut/Application.o"
	@echo "... Walnut/Walnut/src/Walnut/Application.i"
	@echo "... Walnut/Walnut/src/Walnut/Application.s"
	@echo "... Walnut/Walnut/src/Walnut/Image.o"
	@echo "... Walnut/Walnut/src/Walnut/Image.i"
	@echo "... Walnut/Walnut/src/Walnut/Image.s"
	@echo "... Walnut/Walnut/src/Walnut/Random.o"
	@echo "... Walnut/Walnut/src/Walnut/Random.i"
	@echo "... Walnut/Walnut/src/Walnut/Random.s"
	@echo "... Walnut/vendor/imgui/backends/imgui_impl_glfw.o"
	@echo "... Walnut/vendor/imgui/backends/imgui_impl_glfw.i"
	@echo "... Walnut/vendor/imgui/backends/imgui_impl_glfw.s"
	@echo "... Walnut/vendor/imgui/backends/imgui_impl_vulkan.o"
	@echo "... Walnut/vendor/imgui/backends/imgui_impl_vulkan.i"
	@echo "... Walnut/vendor/imgui/backends/imgui_impl_vulkan.s"
	@echo "... Walnut/vendor/imgui/imgui.o"
	@echo "... Walnut/vendor/imgui/imgui.i"
	@echo "... Walnut/vendor/imgui/imgui.s"
	@echo "... Walnut/vendor/imgui/imgui_demo.o"
	@echo "... Walnut/vendor/imgui/imgui_demo.i"
	@echo "... Walnut/vendor/imgui/imgui_demo.s"
	@echo "... Walnut/vendor/imgui/imgui_draw.o"
	@echo "... Walnut/vendor/imgui/imgui_draw.i"
	@echo "... Walnut/vendor/imgui/imgui_draw.s"
	@echo "... Walnut/vendor/imgui/imgui_tables.o"
	@echo "... Walnut/vendor/imgui/imgui_tables.i"
	@echo "... Walnut/vendor/imgui/imgui_tables.s"
	@echo "... Walnut/vendor/imgui/imgui_widgets.o"
	@echo "... Walnut/vendor/imgui/imgui_widgets.i"
	@echo "... Walnut/vendor/imgui/imgui_widgets.s"
	@echo "... WalnutApp/src/WalnutApp.o"
	@echo "... WalnutApp/src/WalnutApp.i"
	@echo "... WalnutApp/src/WalnutApp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

